FROM node:24-alpine

WORKDIR /frontend

COPY frontend/package*.json ./

COPY /shared/package*.json /shared/

COPY /shared  /shared/

RUN cd /shared && npm install && npm run build


COPY /frontend/.env ./ 

RUN npm install


COPY /frontend .


EXPOSE 5000

CMD ["npm","run","dev"]
