FROM node:24-alpine AS build


WORKDIR /app/shared

COPY /shared/package*.json ./

RUN npm install

COPY /shared  .


WORKDIR /app/frontend

COPY frontend/package*.json ./

RUN npm install

COPY /frontend .

COPY /frontend/.env ./ 

RUN npm run build





FROM node:24-alpine

WORKDIR /app

COPY --from=build app/frontend/dist ./dist

RUN npm install -g serve

ENV PORT=5000

EXPOSE 5000

CMD serve -s dist -l ${PORT:-5000}
