FROM node:24-alpine

WORKDIR /app/shared

ENV NODE_ENV=development

RUN apk add --no-cache openssl

COPY /shared/package*.json ./

RUN npm install

COPY /shared .

WORKDIR /app/backend

COPY backend/package*.json ./

RUN npm install

COPY /backend/.env .

COPY /backend . 

RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run","start:docker"]

